name: test:cicd/build

on: [push, pull_request]

jobs:

#  test:
#    name: GO Code Test
#    runs-on: ubuntu-latest
#    steps:
#        - name: Checkout Code
#          uses: actions/checkout@v4
#
#        - name: Setup Go
#          uses: actions/setup-go@v5
#          with:
#            go-version: '1.24.2'
#        - run: go version
#
#        - name: Go Test
#          run: go test -v ./...
#
#        - name: Go Build
#          run: go build ./...
#
#  build:
#    name: Be-answer Image Build And Push
#    runs-on: ubuntu-latest
#    needs:
#          - test
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v4
#
#      - name: Login to Docker
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.ALIYUN_USERNAME }}
#          password: ${{ secrets.ALIYUN_PASSWORD }}
#          registry: crpi-rz6bkoxraz68b1g1.cn-hongkong.personal.cr.aliyuncs.com
#
#      - name: Setup QEMU
#        uses: docker/setup-qemu-action@v3
#
#      - name: Setup Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Build And Push
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          push: true
#          tags: crpi-rz6bkoxraz68b1g1.cn-hongkong.personal.cr.aliyuncs.com/raiki/cicdw:wclg
#          file: ./Dockerfile
#          build-args:
#            Project_Name=be-answer
#            Port=19094

  deploy:
    name: Deploy Be-answer To Server
    runs-on: ubuntu-latest
#    needs:
#      - test
#      - build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_ADDR }} >> ~/.ssh/known_hosts

      - name: SSH into server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_ADDR }} << EOF
          docker pull crpi-rz6bkoxraz68b1g1.cn-hongkong.personal.cr.aliyuncs.com/raiki/cicdw:wclg
          docker image prune -f
          docker compose up -d
          EOF
